KhMedium/Entities/Publication.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhMedium.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.AuthorPublications = new HashSet<AuthorPublication>();
            this.Authors = new HashSet<Author>();
            this.Followers = new HashSet<Follower>();
            this.Followings = new HashSet<Following>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public string Cover { get; set; }
        public string ContactInfo { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorPublication> AuthorPublications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follower> Followers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Following> Followings { get; set; }
    }
}

KhMedium/Models/ViewModel/PublicationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KhMedium.Entities;

namespace KhMedium.Models.ViewModel
{
    public class PublicationViewModel
    {
        public List<AuthorPublication> Publications { get; set; }
    }
}

KhMedium/Areas/Admin/Controllers/PublicationsController.cs
using KhMedium.Controllers;
using KhMedium.Data;
using KhMedium.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KhMedium.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PublicationsController : Controller
    {
        private readonly UnitOfWork _context = new UnitOfWork(new KhMediumEntities());

        // GET: Admin/Publications
        public ActionResult Index()
        {
            var model = _context.Publications.GetAll()
                .Where(p => p.DeletedAt == null);
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Publication publication, HttpPostedFileBase cover, HttpPostedFileBase avatar)
        {
            publication.Id = Guid.NewGuid().ToString();
            publication.CreatedAt = DateTime.Now;
            publication.UpdatedAt = DateTime.Now;
            publication.Cover = FileController.SaveFile(avatar).Path;
            publication.Logo = FileController.SaveFile(cover).Path;
            _context.Publications.Add(publication);
            _context.Complete();
            return RedirectToAction("Index");
        }

        public ActionResult Edits(String id)
        {
            var publication = _context.Publications.Get(id);
            return View(publication);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edits(String id, Publication publication, HttpPostedFileBase cv,
            HttpPostedFileBase avatar)
        {
            if (!ModelState.IsValid)
                return View(publication);
            publication.UpdatedAt = DateTime.Now;
            if (cv != null)
                publication.Cover = FileController.SaveFile(cv).Path;
            if (avatar != null)
                publication.Logo = FileController.SaveFile(avatar).Path;
            _context.Publications.Update(publication);
            _context.Complete();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(String id)
        {
            var publication = _context.Publications.Get(id);
            publication.DeletedAt = DateTime.Now;
            _context.Publications.Update(publication);
            _context.Complete();
            return RedirectToAction("Index");
        }
    }
}

KhMedium/Controllers/PublicationController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using KhMedium.Data;
using KhMedium.Entities;
using KhMedium.Models.ViewModel;
using Microsoft.AspNet.Identity;

namespace KhMedium.Controllers
{
    public class PublicationController : Controller
    {
        private readonly UnitOfWork _context = new UnitOfWork(new KhMediumEntities());

        [Authorize]
        public ActionResult Index()
        {
            var authorPublications = _context.Authors.GetAuthorByUserId(User.Identity.GetUserId()).AuthorPublications.ToList();

            var viewModel = new PublicationViewModel()
            {
                Publications = authorPublications
            };

            return View(viewModel);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(CreatePublicationViewModel model)
        {
            var publication = new Publication();
            publication.Id = Guid.NewGuid().ToString();
            publication.Name = model.Name;
            publication.Description = model.Description;
            publication.Logo = FileController.SaveFile(model.Logo).Path;
            publication.Cover = FileController.SaveFile(model.Cover).Path;
            publication.CreatedAt = DateTime.Now;
            publication.UpdatedAt = DateTime.Now;
            _context.Publications.Add(publication);
            _context.Complete();

            var author = _context.Authors.GetAuthorByUserId(User.Identity.GetUserId());
            var authorPub = new AuthorPublication();
            authorPub.Id = Guid.NewGuid().ToString();
            authorPub.PublicationId = publication.Id;
            authorPub.AuthorId = author?.Id;
            _context.AuthorPublication.Add(authorPub);

            _context.Complete();
            return RedirectToAction("Index", "Publication");
        }
    }
}

KhMedium/Areas/Admin/Views/Publications/Create.cshtml
@model KhMedium.Entities.Publication
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutStart.cshtml";
}
@using (Html.BeginForm("Create", "Publications", FormMethod.Post, new { @Class = "form-horizontal" , enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    {
        @Html.ValidationSummary(true)
        {
            <div class="row">
                <div class="col-sm-6">
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title">បង្កើតសាធារណៈជន</h3>
                        </div>
                        <div class="box-body">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.Label("ឈ្មោះ", htmlAttributes: new { @class = " col-md-3" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("ការពិពណ៌នា", htmlAttributes: new { @class = "col-md-3" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("ទំនាក់ទំនង", htmlAttributes: new { @class = "col-md-3" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ContactInfo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ContactInfo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("គម្រប", htmlAttributes: new { @class = "col-md-3" })
                                <div class="col-md-10">
                                    <input type="file" name="avatar" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("ស្លាកសញ្ញា", htmlAttributes: new { @class = "col-md-3" })
                                <div class="col-md-10">
                                    @*@Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })*@
                                    @*@Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })*@
                                    <input type="file" name="cover" class="form-control" />
                                  
                                </div>
                            </div>
                            <div class="box-footer">
                                @Html.ActionLink("បោះបង់", "Index", "Category", new { @Class = "btn btn-default" })
                                <button type="submit" class="btn btn-info pull-right">រក្សាទុក</button>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        }
    }
}

KhMedium/Areas/Admin/Views/Publications/Edits.cshtml
@model KhMedium.Entities.Publication

@{
    ViewBag.Title = "Edits";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutStart.cshtml";
}

<br />
@using (Html.BeginForm("Edits", "Publications", FormMethod.Post, new { @Class = "form-horizontal" }))
{
    DateTime date = DateTime.Now;
    @Html.AntiForgeryToken()
    {
        @Html.ValidationSummary(true)
        {
            @Html.HiddenFor(model => model.CreatedAt)
            <div class="row">
                <div class="col-sm-6">
                    <div class="box box-info">
                        <div class="box-header">
                            <h3 class="box-title">កែប្រែសាធារណៈជន</h3>
                        </div>
                        <div class="box-body">
                            <div class="form-group">
                                @Html.Label("ឈ្មោះ", htmlAttributes: new { @class = " col-md-3" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("ការពិពណ៌នា", htmlAttributes: new { @class = "col-md-3" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("ទំនាក់ទំនង", htmlAttributes: new { @class = "col-md-3" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ContactInfo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ContactInfo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("គម្រប", htmlAttributes: new { @class = "col-md-3" })
                                <div class="col-md-10">
                                    <input type="file" name="avatar" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("ស្លាកសញ្ញា", htmlAttributes: new { @class = "col-md-3" })
                                <div class="col-md-10">
                                    @*@Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })*@
                                    @*@Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })*@
                                    <input type="file" name="cv" class="form-control" />

                                </div>
                            </div>

                        </div>
                        <div class="box-footer">
                            @Html.ActionLink("បោះបង់", "Index", new { @Class = "btn btn-default" })
                            <button type="submit" class="btn btn-info pull-right">រក្សាទុក</button>
                        </div>
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.Logo)
                        @Html.HiddenFor(model => model.Cover)
                    </div>
                </div>
            </div>
        }
    }
}

KhMedium/Areas/Admin/Views/Publications/Index.cshtml
@model IEnumerable<KhMedium.Entities.Publication>
@using KhMedium.Utils
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutStart.cshtml";
}

@Html.ActionLink("បង្កើត", "Create", "Publications", new { @Class = "btn btn-info pull-right" })
<br />
<br />
<div class="box">
    <div class="box-header">
        <h3 class="box-title">បញ្ជីនៃសាធារណៈជន</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">

        <table id="dataTable" class="table table-bordered table-striped dataTable">
            <thead>

                <tr>
                    <th>លេខរៀង</th>
                    <th>ឈ្មោះ</th>
                    <th>ការពិពណ៌នា</th>
                    <th>ទំនាក់ទំនង</th>
@*                    <th>Avatar</th>*@
                    <th>រូបសញ្ញា</th>
@*                    <th>Create At</th>*@
@*                    <th>Update At</th>*@
                    <th style="width: 20%">សកម្មភាព</th>
                </tr>
            </thead>
            <tbody>
             
            @for (var i = 1; i <= Model.Count(); i++)
            {
                var item = Model.ToList()[i - 1];
                    <tr>
                        <td>@i</td>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td>@item.ContactInfo</td>
                        <td><img src="~/FileUpload/@item.Logo" width="30" height="30"/></td>
@*                        <td><img src="@StringUtils.GetFullImagePath(item.Cover)"  width="30" height="30"/></td>*@
@*                        <td>@item.CreatedAt</td>*@
@*                        <td>@item.UpdatedAt</td>*@
                       
                        <td class="text-center">
                            @Html.ActionLink("កែប្រែ", "Edits", new { id = item.Id }, new { @class = "btn btn-warning" })
                            @Html.ActionLink("លុប", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
    <!-- /.box-body -->
</div>

@Scripts.Render("~/bundles/jquery")
<script>
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "order": [[1, "asc"]]
        });
    });
</script>