KhMedium/Entities/Publication.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhMedium.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.AuthorPublications = new HashSet<AuthorPublication>();
            this.Authors = new HashSet<Author>();
            this.Followers = new HashSet<Follower>();
            this.Followings = new HashSet<Following>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public string Cover { get; set; }
        public string ContactInfo { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorPublication> AuthorPublications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follower> Followers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Following> Followings { get; set; }
    }
}

KhMedium/Models/ViewModel/PublicationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KhMedium.Entities;

namespace KhMedium.Models.ViewModel
{
    public class PublicationViewModel
    {
        public List<AuthorPublication> Publications { get; set; }
    }
}

KhMedium/Models/ViewModel/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KhMedium.Entities;

namespace KhMedium.Models.ViewModel
{
    public class SearchViewModel
    {
        public String Query { get; set; }
        public List<Author> Users { get; set; }
        public List<Publication> Publications { get; set; }
        public List<Article> Articles { get; set; }
        public String Type { get; set; }
    }
}

KhMedium/Areas/Admin/Controllers/PublicationsController.cs
using KhMedium.Controllers;
using KhMedium.Data;
using KhMedium.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KhMedium.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PublicationsController : Controller
    {
        private readonly UnitOfWork _context = new UnitOfWork(new KhMediumEntities());

        // GET: Admin/Publications
        public ActionResult Index()
        {
            var model = _context.Publications.GetAll()
                .Where(p => p.DeletedAt == null);
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Publication publication, HttpPostedFileBase cover, HttpPostedFileBase avatar)
        {
            publication.Id = Guid.NewGuid().ToString();
            publication.CreatedAt = DateTime.Now;
            publication.UpdatedAt = DateTime.Now;
            publication.Cover = FileController.SaveFile(avatar).Path;
            publication.Logo = FileController.SaveFile(cover).Path;
            _context.Publications.Add(publication);
            _context.Complete();
            return RedirectToAction("Index");
        }

        public ActionResult Edits(String id)
        {
            var publication = _context.Publications.Get(id);
            return View(publication);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edits(String id, Publication publication, HttpPostedFileBase cv,
            HttpPostedFileBase avatar)
        {
            if (!ModelState.IsValid)
                return View(publication);
            publication.UpdatedAt = DateTime.Now;
            if (cv != null)
                publication.Cover = FileController.SaveFile(cv).Path;
            if (avatar != null)
                publication.Logo = FileController.SaveFile(avatar).Path;
            _context.Publications.Update(publication);
            _context.Complete();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(String id)
        {
            var publication = _context.Publications.Get(id);
            publication.DeletedAt = DateTime.Now;
            _context.Publications.Update(publication);
            _context.Complete();
            return RedirectToAction("Index");
        }
    }
}

KhMedium/Controllers/PublicationController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using KhMedium.Data;
using KhMedium.Entities;
using KhMedium.Models.ViewModel;
using Microsoft.AspNet.Identity;

namespace KhMedium.Controllers
{
    public class PublicationController : Controller
    {
        private readonly UnitOfWork _context = new UnitOfWork(new KhMediumEntities());

        [Authorize]
        public ActionResult Index()
        {
            var authorPublications = _context.Authors.GetAuthorByUserId(User.Identity.GetUserId()).AuthorPublications.ToList();

            var viewModel = new PublicationViewModel()
            {
                Publications = authorPublications
            };

            return View(viewModel);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(CreatePublicationViewModel model)
        {
            var publication = new Publication();
            publication.Id = Guid.NewGuid().ToString();
            publication.Name = model.Name;
            publication.Description = model.Description;
            publication.Logo = FileController.SaveFile(model.Logo).Path;
            publication.Cover = FileController.SaveFile(model.Cover).Path;
            publication.CreatedAt = DateTime.Now;
            publication.UpdatedAt = DateTime.Now;
            _context.Publications.Add(publication);
            _context.Complete();

            var author = _context.Authors.GetAuthorByUserId(User.Identity.GetUserId());
            var authorPub = new AuthorPublication();
            authorPub.Id = Guid.NewGuid().ToString();
            authorPub.PublicationId = publication.Id;
            authorPub.AuthorId = author?.Id;
            _context.AuthorPublication.Add(authorPub);

            _context.Complete();
            return RedirectToAction("Index", "Publication");
        }
    }
}

KhMedium/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KhMedium.Models.ViewModel;

namespace KhMedium.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index(String q)
        {
            var model = new SearchViewModel();
            model.Query = q;
            model.Type = "stories";
            return View(model);
        }

        public ActionResult Users(String q)
        {
            var model = new SearchViewModel();
            model.Query = q;
            model.Type = "stories";
            return View(model);
        }

        public ActionResult Publications(String q)
        {
            var model = new SearchViewModel();
            model.Query = q;
            model.Type = "publication";
            return View(model);
        }
       
    }
}

KhMedium/Views/Search/Index.cshtml
@model KhMedium.Models.ViewModel.SearchViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .textInput--underlined {
        border: 0;
        border-bottom: 1px solid rgba(0, 0, 0, .15);
        -webkit-border-radius: 0;
        border-radius: 0;
    }

    .textInput--jumbo {
        font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
        letter-spacing: 0;
        font-weight: 300;
        font-style: normal;
        font-size: 52px;
        height: 80px;
        padding: 0;
        width: 100%;
    }

    form {
        display: block;
        margin-top: 0em;
    }

    input[type=search] {
        -webkit-appearance: none;
        -webkit-box-sizing: content-box;
        box-sizing: content-box;
    }

    blockquote, dd, dl, figure, form, h1, h2, h3, h4, h5, h6, menu, ol, p, pre, ul { margin: 0; }

    input { outline: none; }

    .space { margin: 8px; }
   
</style>


@using (Html.BeginForm("Index", "Search", FormMethod.Get, new {enctype = "multipart/form-data"}))
{
    <div class="container">
        <input type="search" placeholder="Search" name="q" class="js-searchInput textInput textInput--jumbo textInput--underlined">
        <br/>
    <br/>
        @Html.ActionLink("Stories", "Index", "Search", htmlAttributes: new {@class = "btn btn-info btn-sm", q = Model.Query})
        @Html.ActionLink("People", "Users", "Search", htmlAttributes: new {@class = "btn btn-primary btn-sm", q = Model.Query})
        @Html.ActionLink("Publications", "Publications", "Search", htmlAttributes: new {@class = "btn btn-primary btn-sm", q = Model.Query})
        
        <br />
        <br />
        <div class="row justify-content-between">
            <div class="col-md-8">
                <h5 class="font-weight-bold spanborder">
                    <span>Stories</span>
                </h5>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">Nearly 200 Great Barrier Reef coral species also live in the deep sea</a>
                        </h2>
                        <p>
                            There are more coral species lurking in the deep ocean that previously thought.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/blog8.jpg">
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">East Antarctica's glaciers are stirring</a>
                        </h2>
                        <p>
                            Nasa says it has detected the first signs of significant melting in a swathe of glaciers in East Antarctica.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/1.jpg">
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">50 years ago, armadillos hinted that DNA wasn’t destiny</a>
                        </h2>
                        <p>
                            Nasa says it has detected the first signs of significant melting in a swathe of glaciers in East Antarctica.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/5.jpg">
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">Nearly 200 Great Barrier Reef coral species also live in the deep sea</a>
                        </h2>
                        <p>
                            There are more coral species lurking in the deep ocean that previously thought.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/blog8.jpg">
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">East Antarctica's glaciers are stirring</a>
                        </h2>
                        <p>
                            Nasa says it has detected the first signs of significant melting in a swathe of glaciers in East Antarctica.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/1.jpg">
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">50 years ago, armadillos hinted that DNA wasn’t destiny</a>
                        </h2>
                        <p>
                            Nasa says it has detected the first signs of significant melting in a swathe of glaciers in East Antarctica.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/5.jpg">
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">Nearly 200 Great Barrier Reef coral species also live in the deep sea</a>
                        </h2>
                        <p>
                            There are more coral species lurking in the deep ocean that previously thought.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/blog8.jpg">
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">East Antarctica's glaciers are stirring</a>
                        </h2>
                        <p>
                            Nasa says it has detected the first signs of significant melting in a swathe of glaciers in East Antarctica.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/1.jpg">
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="pr-3">
                        <h2 class="mb-1 h4 font-weight-bold">
                            <a class="text-dark" href="article.html">50 years ago, armadillos hinted that DNA wasn’t destiny</a>
                        </h2>
                        <p>
                            Nasa says it has detected the first signs of significant melting in a swathe of glaciers in East Antarctica.
                        </p>
                        <div class="card-text text-muted small">
                            Jake Bittle in SCIENCE
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    <img height="120" src="~/Content/assets/img/demo/5.jpg">
                </div>
            </div>
            <div class="col-md-4 pl-4">
                <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="205">
                    <h5 class="font-weight-bold spanborder">
                        <span>Popular</span>
                    </h5>
                    <ol class="list-featured">
                        <li>
                            <span>
                                <h6 class="font-weight-bold">
                                    <a href="article.html" class="text-dark">Did Supernovae Kill Off Large Ocean Animals?</a>
                                </h6>
                                <p class="text-muted">
                                    Jake Bittle in SCIENCE
                                </p>
                            </span>
                        </li>
                        <li>
                            <span>
                                <h6 class="font-weight-bold">
                                    <a href="article.html" class="text-dark">Humans Reversing Climate Clock: 50 Million Years</a>
                                </h6>
                                <p class="text-muted">
                                    Jake Bittle in SCIENCE
                                </p>
                            </span>
                        </li>
                        <li>
                            <span>
                                <h6 class="font-weight-bold">
                                    <a href="article.html" class="text-dark">Unprecedented Views of the Birth of Planets</a>
                                </h6>
                                <p class="text-muted">
                                    Jake Bittle in SCIENCE
                                </p>
                            </span>
                        </li>
                        <li>
                            <span>
                                <h6 class="font-weight-bold">
                                    <a href="article.html" class="text-dark">Effective New Target for Mood-Boosting Brain Stimulation Found</a>
                                </h6>
                                <p class="text-muted">
                                    Jake Bittle in SCIENCE
                                </p>
                            </span>
                        </li>
                    </ol>
                </ul>
            </div>
        </div>
    </div>
}

KhMedium/Views/Search/Publications.cshtml
@{
    ViewBag.Title = "Publications";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

KhMedium/Views/Search/Users.cshtml
@model KhMedium.Models.ViewModel.SearchViewModel
@{
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .textInput--underlined {
        border: 0;
        border-bottom: 1px solid rgba(0, 0, 0, .15);
        -webkit-border-radius: 0;
        border-radius: 0;
    }

    .textInput--jumbo {
        font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
        letter-spacing: 0;
        font-weight: 300;
        font-style: normal;
        font-size: 52px;
        height: 80px;
        padding: 0;
        width: 100%;
    }

    form {
        display: block;
        margin-top: 0em;
    }

    input[type=search] {
        -webkit-appearance: none;
        -webkit-box-sizing: content-box;
        box-sizing: content-box;
    }

    blockquote, dd, dl, figure, form, h1, h2, h3, h4, h5, h6, menu, ol, p, pre, ul { margin: 0; }

    input { outline: none; }

    .space { margin: 8px; }

    .col {
        position: relative;
        min-height: 1px;
        padding-right: 20px;
        padding-left: 20px;
    }

    .col, .container, .row {
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }

    .u-size9of12 { width: 75% !important; }

    .u-size10of12, .u-size11of12, .u-size12of12, .u-size1of12, .u-size2of12, .u-size3of12, .u-size4of12, .u-size5of12, .u-size6of12, .u-size7of12, .u-size8of12, .u-size9of12 { float: left !important; }

    div { display: block; }

    .heading--allCaps, .heading-prefix {
        font-size: 15px;
        letter-spacing: .1em;
        text-transform: uppercase;
    }

    .heading--borderedTop { border-top: 1px solid rgba(0, 0, 0, .05); }

    .heading {
        color: rgba(0, 0, 0, .84);
        font-size: 18px;
        letter-spacing: 0;
        position: relative;
    }

    article, aside, details, figcaption, figure, footer, header, hgroup, main, menu, nav, section, summary { display: block; }

    article, aside, footer, header, hgroup, main, nav, section { display: block; }
    .u-marginBottom50 {
        margin-bottom: 50px!important;
    }
    .u-marginTop10 {
        margin-top: 10px!important;
    }
    menu, ol, ul {
        padding: 0;
        list-style: none;
        list-style-image: none;
    }
    blockquote, dd, dl, figure, form, h1, h2, h3, h4, h5, h6, menu, ol, p, pre, ul {
        margin: 0;
    }
   
    .uiScale {
        line-height: 20px;
        font-size: 16px;
    }
    .u-paddingBottom18 {
        padding-bottom: 18px!important;
    }
    .u-block {
        display: block!important;
    }
li {
        display: list-item;
        text-align: -webkit-match-parent;
    }
    .u-marginLeft20 {
        margin-left: 20px!important;
    }

    .u-floatRight {
        float: right!important;
    }
div {
        display: block;
    }
    .u-tableCell {
        display: table-cell!important;
    }
    .u-breakWord {
        word-break: break-word;
        word-wrap: break-word;
    }
    .u-paddingLeft15 {
        padding-left: 15px!important;
    }
    .u-tableCell {
        display: table-cell!important;
    }
    .u-verticalAlignMiddle {
        vertical-align: middle!important;
    }
div {
        display: block;
    }
    .uiScale {
        line-height: 20px;
        font-size: 16px;
    }
li {
        display: list-item;
        text-align: -webkit-match-parent;
    }
   
</style>


@using (Html.BeginForm("Index", "Search", FormMethod.Get, new {enctype = "multipart/form-data"}))
{
    <div class="container">
        <input type="search" placeholder="Search" name="q" class="js-searchInput textInput textInput--jumbo textInput--underlined">
        <br/>
        <br/>
        @Html.ActionLink("Stories", "Index", "Search", htmlAttributes: new {@class = "btn btn-primary btn-sm", q = Model.Query})
        @Html.ActionLink("People", "Users", "Search", htmlAttributes: new {@class = "btn btn-info btn-sm", q = Model.Query})
        @Html.ActionLink("Publications", "Publications", "Search", htmlAttributes: new {@class = "btn btn-primary btn-sm", q = Model.Query})

        <br/>
        <br/>

        <div class="col u-size9of12 u-sm-size12of12">
            <header class="heading heading--borderedTop heading--allCaps u-sm-hide">
                <div class="u-clearfix">
                    <div class="heading-content u-floatLeft">
                        <span class="heading-title heading-title--bold"></span>
                    </div>
                </div>
            </header>
            <ul class="u-clearfix u-marginTop10 u-marginBottom50 js-userResultsList">
                <li
                    class="uiScale uiScale-ui--small uiScale-caption--regular u-block u-paddingBottom18 js-cardUser">
                    <div class="u-marginLeft20 u-floatRight">
                        <span class="followState js-followState" data-user-id="77ce6c03c7fe">
                            <button
                                class="button button--small u-noUserSelect button--withChrome u-baseColor--buttonNormal button--withHover button--unblock js-unblockButton"
                                data-action="toggle-block-user"
                                data-action-value="77ce6c03c7fe"
                                data-action-source="search_user">
                                <span class="button-label  button-defaultState">Blocked</span
                                ><span class="button-label button-hoverState">Unblock</span>
                            </button
                            ><button
                                 class="button button--primary button--small u-noUserSelect button--withChrome u-accentColor--buttonNormal button--follow js-followButton"
                                 data-action="toggle-subscribe-user"
                                 data-action-value="77ce6c03c7fe"
                                 data-action-source="search_user-77ce6c03c7fe-------------------------follow_search"
                                 data-subscribe-source="search_user">
                                <span class="button-label  button-defaultState js-buttonLabel">Follow</span
                                ><span class="button-label button-activeState">Following</span>
                            </button>
                        </span
                        >
                    </div>
                    <div class="u-tableCell">
                        <a
                            class="link u-baseColor--link avatar">
                            <img
                                src="https://cdn-images-1.medium.com/fit/c/66/66/0*_Hb822l12dby3Y4v.jpeg"
                                class="avatar-image avatar-image--small"/>
                        </a>
                    </div>
                    <div
                        class="u-tableCell u-verticalAlignMiddle u-breakWord u-paddingLeft15">
                        <h3 class="ui-h3 u-fontSize18 u-lineHeightTighter u-marginBottom4">
                            <a
                                class="link link--primary u-accentColor--hoverTextNormal">
                                Kerri Jablonski
                            </a
                            >
                        </h3>
                        <p
                            class="ui-body u-fontSize14 u-lineHeightBaseSans u-textColorDark u-marginBottom4">
                            I don't write, I ramble. Mom-Influencer #ASD #prematurity #NoiseGirl
                            #AVENTmoms #DisneySMMoms
                            <a rel="nofollow" href="mailto:press@themavenofsocialmedia.com">press@themavenofsocialmedia.com</a
                            >
                            RTs aren't endorsements
                        </p>
                    </div>
                </li>
            </ul>
        </div>


    </div>
}