KhMedium/Entities/Article.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhMedium.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleTags = new HashSet<ArticleTag>();
            this.Bookmarks = new HashSet<Bookmark>();
            this.Claps = new HashSet<Clap>();
            this.Comments = new HashSet<Comment>();
            this.Shares = new HashSet<Share>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Thumbnail { get; set; }
        public string TopicId { get; set; }
        public string AuthorId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Topic Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleTag> ArticleTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clap> Claps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Share> Shares { get; set; }
    }
}

KhMedium/Areas/Admin/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KhMedium.Entities;
using System.Web.Mvc;
using KhMedium.Controllers;
using KhMedium.Data;
using KhMedium.Models.ViewModel;
using Microsoft.AspNet.Identity;

namespace KhMedium.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ArticlesController : Controller
    {
        private readonly UnitOfWork _context = new UnitOfWork(new KhMediumEntities());


        // GET: Admin/Articles
        public ActionResult Index()
        {
            var articles = _context.Articles.GetAll()
                .Where(d => d.DeletedAt == null);
            return View(articles);
        }

        public ActionResult Create()
        {
            var model = new CreateArticleViewModel
            {
                Topics = _context.Topics.GetAll().ToList()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CreateArticleViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            var userId = User.Identity.GetUserId();
            var author = _context.Authors.GetAuthorByUserId(userId);
            var article = new Article();
            article.Id = Guid.NewGuid().ToString();
            article.Title = model.Title;
            article.TopicId = model.TopicId;
            article.Content = model.Content;
            article.AuthorId = author.Id;
            article.CreatedAt = DateTime.Now;
            article.UpdatedAt = DateTime.Now;

            var thumnail = FileController.SaveFile(model.ArticlesImage);
            article.Thumbnail = thumnail.Path;
            _context.Articles.Add(article);
            _context.Complete();
            return RedirectToAction("Index");
        }

        public ActionResult Edits(String id)
        {
            var article = _context.Articles.Get(id);
            var model = new CreateArticleViewModel
            {
                Id =  article.Id,
                Title = article.Title,
                Content = article.Content,
                TopicId = article.TopicId,
                ImageName = article.Thumbnail,
                Topics = _context.Topics.GetAll().ToList()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edits(String id, CreateArticleViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);
            var article = _context.Articles.Get(viewModel.Id);
            article.Title = viewModel.Title;
            article.Content = viewModel.Content;
            article.TopicId = viewModel.TopicId;
            article.UpdatedAt = DateTime.Now;
            if(viewModel.ArticlesImage != null)
                article.Thumbnail = FileController.SaveFile(viewModel.ArticlesImage).Path;
            _context.Articles.Update(article);
            _context.Complete();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(String id)
        {
            var articles = _context.Articles.Get(id);
            articles.DeletedAt = DateTime.Now;
            _context.Complete();
            return RedirectToAction("Index");
        }
    }
}

KhMedium/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KhMedium.Data;
using KhMedium.Entities;
using KhMedium.Models.ViewModel;
using Microsoft.AspNet.Identity;

namespace KhMedium.Controllers
{
    public class ArticleController : Controller
    {
        private readonly UnitOfWork _context = new UnitOfWork(new KhMediumEntities());

        // GET: Article
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            var model = new CreateArticleViewModel
            {
                Topics = _context.Topics.GetAll().ToList()
            };


            return View(model);
        }

        [HttpPost]
        public ActionResult CreateArticle(CreateArticleViewModel model)
        {
            var file = Request.Files[0];
            //Foreign Keys are simulated for simplicity
            var article = new Article();
            article.Id = Guid.NewGuid().ToString();
            article.Title = model.Title;
            article.TopicId = model.TopicId;
            article.Content = model.Content;
            Console.WriteLine(User.Identity.GetUserId());
            article.AuthorId = _context.Authors.GetAuthorByUserId(User.Identity.GetUserId()).Id;
            article.CreatedAt = DateTime.Now;
            article.UpdatedAt = DateTime.Now;

            var thumbnail = FileController.SaveFile(model.ArticlesImage);
            article.Thumbnail = thumbnail.Path;
            _context.Articles.Add(article);
            _context.Complete();

            return RedirectToAction("Index", "Home");
        }

    }
}

KhMedium/Views/Article/Create.cshtml
@model KhMedium.Models.ViewModel.CreateArticleViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

    WebImage photo = null;
    var newFileName = "";
    var imagePath = "";

    if (IsPost)
    {
        photo = WebImage.GetImageFromRequest();

        if (photo != null)
        {
            newFileName = Guid.NewGuid().ToString() + "_" +
                          Path.GetFileName(photo.FileName);
            imagePath = @"images\" + newFileName;
            photo.Save(@"~\" + imagePath);
        }
    }

}
<style>
    .margin-top60 {
        margin-top: 60px;
    }

    .title {
        border: 0;
        box-shadow: none;
    }

        .title:focus {
            outline: none;
            border: 0;
            box-shadow: none;
        }

    .input-border-bottom {
        padding-bottom: 2px;
        border-bottom: 1px solid rgba(0, 0, 0, .15);
        padding: 0 0;
        margin-left: 15px;
        margin-right: 15px;
    }

    .form-control-plaintext {
        outline: 0;
        box-shadow: none;
    }

    label:focus {
        outline: 0 !important;
        -webkit-appearance: none;
    }

    input:focus {
        outline: 0 !important;
        -webkit-appearance: none;
    }

    .none-padding-left {
        padding-left: 0;
    }

    .btn-save {
        margin-top: 30px;
        margin-bottom: 30px;
        float: right !important;
        padding: 10px 30px;
        background: none;
        color: rgba(148, 0, 211, .7);
        border: 1px solid rgba(148, 0, 211, .7);
    }

        .btn-save:hover {
            color: rgb(148, 0, 211);
            border: 1px solid rgb(148, 0, 211);
        }

        .btn-save:focus {
            color: rgb(148, 0, 211);
            border: 1px solid rgb(148, 0, 211);
        }

    .btn-file {
        position: relative;
        overflow: hidden;
        background-color: rgb(148, 0, 211);
        color: white;
        margin: 10px 10px;
    }

        .btn-file input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            min-width: 100%;
            min-height: 100%;
            font-size: 100px;
            text-align: right;
            filter: alpha(opacity=0);
            opacity: 0;
            outline: none;
            background: white;
            cursor: inherit;
            display: block;
        }

    .topic {
        border: 1px solid #ced4da;
        margin-left: 15px;
        margin-right: 15px;
    }

    .margin-top30 {
        margin-top: 30px;
    }
</style>
@using (Html.BeginForm("CreateArticle", "Article", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row">
            <h1 class="col-md-12">បង្កើតអត្ថបទ</h1>
            <div class="col-md-12 form-group row margin-top60">
                <div class="col-md-12 input-border-bottom">
                    <input type="text" name="Title" class="form-control title" placeholder="ចំណងជើង">
                </div>
            </div>
            <div class="col-md-12">
                <label for="Image">រូបដំណាងអត្ថបទ</label>
                <span class="btn btn-default btn-file">
                    រកមើល <input type="file" name="ArticlesImage">
                </span>
                <label id="fileName"></label>
                <br />
            </div>
            @Html.DropDownListFor(x => Model.TopicId, new SelectList(Model.Topics, "Id", "Name"), htmlAttributes: new { @class = "form-control topic" })
            <div class="col-md-12 margin-top30">
                <textarea name="Content"></textarea>
            </div>
            <div class="col-md-12 none-padding-left  margin-top60">
                <button class="btn btn-save">រក្សាទុក</button>
            </div>
        </div>

    </div>
}
@Scripts.Render("~/bundles/jquery")
<script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Content');
    $(document).ready(function () {
        $('input[type="file"]').change(function (e) {
            var fileName = e.target.files[0].name;
            $("#fileName").text(fileName);
        });
    });
</script>

KhMedium/Views/Article/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //<link rel="stylesheet" href="~/Views/Article/css/samples.css">
    //<link rel="stylesheet" href="~/Views/Article/css/codemirror/neo.css">
}

@*@section Styles{
    <link href="@Url.Content("~/Content/pages/Article/css/samples.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/pages/Article/css/codemirror/neo.css")" rel="stylesheet" type="text/css" />
}*@




<h2>Index</h2>
<textarea name="editor1"></textarea>
@section scripts{
@*<script src="https://cdn.ckeditor.com/ckeditor5/11.2.0/classic/ckeditor.js"></script>*@
<script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor1');
</script>
    }





@*@section scripts{
    <script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>
    <script src="https://cdn.ckeditor.com/[version.number]/[distribution]/ckeditor.js"></script>
    <script>
        CKEDITOR.plugins.addExternal('abbr', '/myplugins/abbr/', 'plugin.js');

        // extraPlugins needs to be set too.
        CKEDITOR.replace('editor1', {
            extraPlugins: 'abbr'
        });
    </script>
   ]*@